### ISSUE TITLE
NA+tcp issue

### ISSUE THREAD

**Issue by jiayulu** [mercury-hpc/mercury#155]
here's the trace from libasan:

[1,0]<stderr>:==9311==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x7fc908c26a81 sp 0x7fff1118a600 bp 0x000000000000 T0)
[1,0]<stderr>:    #0 0x7fc908c26a80 in OPA_fetch_and_add_int /scratch/jenkins-2/artifacts/mercury-update-scratch/240/openpa/include/primitives/opa_gcc_intel_32_64_ops.h:127
[1,0]<stderr>:    #1 0x7fc908c26a80 in OPA_fetch_and_decr_int /scratch/jenkins-2/artifacts/mercury-update-scratch/240/openpa/include/primitives/opa_emulated.h:120
[1,0]<stderr>:    #2 0x7fc908c26a80 in hg_atomic_decr32 /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/util/mercury_atomic.h:136
[1,0]<stderr>:    #3 0x7fc908c26a80 in op_id_decref /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/na/na_cci.c:784
[1,0]<stderr>:    #4 0x7fc908c26a80 in na_cci_op_destroy /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/na/na_cci.c:662
[1,0]<stderr>:    #5 0x7fc908c26a80 in na_cci_msg_recv_expected /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/na/na_cci.c:1298
[1,0]<stderr>:    #6 0x7fc908e310fd in hg_core_forward_na /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/mercury_core.c:1322
[1,0]<stderr>:    #7 0x7fc908e310fd in HG_Core_forward /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/mercury_core.c:3206
[1,0]<stderr>:    #8 0x7fc908e32353 in HG_Forward /var/lib/jenkins/wolf-50vm4-jenkins-2-1-el7-x8664/workspace/mercury-update-scratch/mercury/src/mercury.c:1153
[1,0]<stderr>:    #9 0x7fc90992200e in crt_hg_req_send src/crt/crt_hg.c:797
[1,0]<stderr>:    #10 0x7fc90993e359 in crt_req_send src/crt/crt_rpc.c:495
[1,0]<stderr>:    #11 0x40209f in run_echo_srver src/test/crt_echo_srv.c:91
[1,0]<stderr>:    #12 0x40209f in main src/test/crt_echo_srv.c:223
[1,0]<stderr>:    #13 0x7fc908477b14 in __libc_start_main (/usr/lib64/libc.so.6+0x21b14)
[1,0]<stderr>:    #14 0x402854 (/home/yulujia/codes/cart/install/Linux/TESTING/tests/crt_echo_srv+0x402854)

**Comment by jiayulu** [comment]
this is using cci 4e655d1, Mercury 70099db.

**Comment by jiayulu** [comment]
rebasing our cci patch solved this.
